export const LANG_KO_NAME = 'ko';
export const LANG_KO_MSGS = {
    'notSelectedUser' : '구매자를 선택해주세요.',
    'addedABO' : '추가된 ABO번호 입니다.',
    'noCartInfo' : '장바구니 정보가 없습니다. 제품을 추가해 주세요.',
    'posNotSet': '미등록 POS 기기입니다.<br>IT 관리자에게 문의하여 주시기 바랍니다.<br>IT서비스 데스크 (<em class="fc_red">02-3468-6119</em>)',
    'changeUserAlert' : '현재 장바구니의 사용자를 변경하시겠습니까?',
    'noECPOrder' : 'ECP 주문건이 없습니다.',
    'limitECPOrder' : '회원이 2건 이상의 ECP 주문이 있습니다.<br>주문완료 내역에서 검색해주세요.',
    'selectProductDelete' : '삭제할 제품을 선택 해 주세요.',
    'selectProductUpdate' : '수정할 제품을 선택 해 주세요.',
    'notinputPaid' : '내신 금액을 입력해 주세요.',
    'notEnoughPaid' : '내신 금액이 결제금액보다 작습니다.',
    'noSearchText' : '검색어를 입력해주세요.',
    'receiptComplete' : '영수증 발행이 완료되었습니다.',
    'ecpReceiptComplete' : '픽업 주문 영수증 출력이 완료되었습니다.',
    'receiptFail' : '영수증 발행이 실패되었습니다.',
    'coupon.already.redeemed': '쿠폰 코드가 이미 사용되었습니다.',
    'coupon.invalid.code.provided': '쿠폰 코드가 유효하지 않습니다',
    'coupon.order.recalculation.error': '주문을 다시 계산하는 중 오류가 발생했습니다.',
    'coupon.not.active.expired': '쿠폰 코드가 더 이상 유효하지 않습니다.',
    'coupon.general.error': '쿠폰 코드의 유효성 검사에 실패했습니다.',
    'coupon.already.exists.cart': '쿠폰 코드가 장바구니에 이미 적용되었습니다.',
    'cancelReceiptComplete' : '취소 영수증 발행이 완료되었습니다',
    'cancelReceiptFail' : '취소 영수증 발행이 실패되었습니다.',
    'payment.success': '결제가 완료되었습니다.',
    'payment.success.next': '결제가 완료되었습니다. 다음 결제 수단을 선택해주세요.',
    'payment.fail': '결제에 실패했습니다.',
    'card.payment.success': '카드결제 승인이 완료되었습니다.',
    'card.payment.success.next': '카드결제 승인이 완료되었습니다. 다음 결제 수단을 선택해주세요.',
    'credit.valid.overpaid': '실결제금액이 총 매출보다 큽니다.',
    'credit.valid.smallpaid': '실결제금액이 총 매출보다 작습니다.',
    'no.accountnumber': '계좌번호가 없습니다. 계좌번호를 확인하시기 바랍니다.',
    'empty.password': '비밀번호가 공란입니다.',
    'notuse.directdeit': '즉시 출금이 불가합니다. 다른 결제 수단을 이용해주세요.',
    'abo.point.label': 'A포인트',
    'member.point.label': 'Member 포인트',
    'point.overpaid': '사용 포인트가 결제금액보다 많습니다.',
    'point.smallpaid': '사용 포인트가 결제금액보다 작습니다.',
    'point.use.over': '가용포인트 보다 사용포인트가 클 수 없습니다.',
    'point.empty': '사용 포인트가 공란입니다.',
    'recash.smallpaid': '결제 사용할 금액이 부족합니다.',
    'recash.overpaid': '잔액보다 사용하려는 금액이 클 수 없습니다.',
    'recash.lack': '사용가능한 Re-Cash보다 사용할 금액이 클 수 없습니다.',
    'empty.coupon': '검색할 쿠폰번호를 입력해주세요.',
    'noresult.coupon': '쿠폰이 존재하지 않습니다. 쿠폰번호를 다시 확인해주세요.',
    'not.choose.payment': '주결제 수단이 선택되지 않았습니다. 다시 결제를 진행해주세요.',
    'no.point': '{0}님의 포인트가 없습니다.<br>다른 결제수단을 선택해주세요.',
    'no.recash': '{0}님의 Re-Cash가 없습니다.<br>다른 결제수단을 선택해주세요.',
    'default.order.type': '현장구매',
    'deduction.msg': '공제조합홈페이지 확인',
    'receipt.apoint.label': '포인트차감(A포인트)',
    'receipt.mpoint.label': '포인트차감(멤버포인트)',
    'receipt.reg.number.emp': '고객번호를 입력해주세요.',
    'receipt.reg.number.biz': '고객번호를 입력해주세요.',
    'receipt.reg.number.success': '영수증 신청이 정상적으로 처리되었습니다.',
};
